version: '3'
services:
  flask:
    image: mak071/flask_app.py:v0.2
    hostname: mak_flask
    scale: 2
  nginx:
    image: nginxinc/nginx-unprivileged:latest 
    ports:
      - "80:80"
      - "443:443"                        
    volumes:
      - ./example.key:/etc/nginx/ssl/example.key
      - ./example.crt:/etc/nginx/ssl/example.crt
      #- ./nginx.conf:/etc/nginx/nginx.conf
      - ./templates/nginx.conf.template:/etc/nginx/templates/nginx.conf.template       
    environment:      
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template                
      - ENV_TXT="Default text message from template"       
    user: nginx 
    depends_on:
      - flask      
